// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BirdCaseShop.Models
{
    public partial class Payment
    {
        [Key]
        [Column("PaymentID")]
        [StringLength(50)]
        public string PaymentId { get; set; }
        [Required]
        [Column("OrderID")]
        [StringLength(10)]
        public string OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTime { get; set; }
        [Column("amout", TypeName = "decimal(18, 0)")]
        public decimal Amout { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreateDate { get; set; }
        public bool Status { get; set; }
        [Required]
        public string TransactionCode { get; set; }
        [Required]
        [Column("vnp_TransDate")]
        public string VnpTransDate { get; set; }

        [ForeignKey("OrderId")]
        [InverseProperty("Payment")]
        public virtual Order Order { get; set; }
    }
}