// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BirdCaseShop.Models
{
    public partial class Size
    {
        public Size()
        {
            Bird = new HashSet<Bird>();
            Material = new HashSet<Material>();
            ProductCustom = new HashSet<ProductCustom>();
            SizeProduct = new HashSet<SizeProduct>();
        }

        [Key]
        [Column("SizeID")]
        [StringLength(10)]
        public string SizeId { get; set; }
        [Required]
        [Column("Size")]
        [StringLength(10)]
        public string Size1 { get; set; }
        [Column("StyleID")]
        [StringLength(10)]
        public string StyleId { get; set; }
        public bool IsCustom { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }

        [ForeignKey("StyleId")]
        [InverseProperty("Size")]
        public virtual Style Style { get; set; }
        [InverseProperty("BirdSizeNavigation")]
        public virtual ICollection<Bird> Bird { get; set; }
        [InverseProperty("Size")]
        public virtual ICollection<Material> Material { get; set; }
        [InverseProperty("ProductSizeNavigation")]
        public virtual ICollection<ProductCustom> ProductCustom { get; set; }
        [InverseProperty("Size")]
        public virtual ICollection<SizeProduct> SizeProduct { get; set; }
    }
}