// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BirdCaseShop.Models
{
    public partial class Voucher
    {
        public Voucher()
        {
            VoucherUserOrder = new HashSet<VoucherUserOrder>();
        }

        [Key]
        [Column("VoucherID")]
        [StringLength(10)]
        public string VoucherId { get; set; }
        [Required]
        [StringLength(50)]
        public string VoucherName { get; set; }
        public int Discount { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime EndDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreateAt { get; set; }
        [Required]
        [Column("ImageURL")]
        public string ImageUrl { get; set; }
        public int Quantity { get; set; }
        public int CountVoucher { get; set; }
        public bool Status { get; set; }

        [InverseProperty("Voucher")]
        public virtual ICollection<VoucherUserOrder> VoucherUserOrder { get; set; }
    }
}